name: Update News  # Nombre del workflow: "Actualizar Noticias"

on:
  schedule:
    - cron: '0 */6 * * *'  # Se ejecuta cada 6 horas automáticamente
  push:
    branches: [ main ]  # También se ejecuta al hacer push a main

jobs:
  update:
    runs-on: ubuntu-latest  # Usa un servidor Linux gratis de GitHub

    steps:
    - name: Checkout repo  # Descarga tu repo
      uses: actions/checkout@v4

    - name: Set up Python  # Configura Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies  # Instala feedparser para leer RSS
      run: pip install feedparser

    - name: Generate noticias.html  # Corre tu script Python
      run: python generar_noticias.py

    - name: Commit changes  # Sube el archivo generado si cambió
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add noticias.html
        git commit -m "Actualizar noticias RSS" || echo "No changes"
        git push
