name: Update News
on:
  schedule:
    - cron: '*/5 * * * *' # Cada 5 minutos
  push:
    branches: [ main ]
permissions:
  contents: write  # Permite commit y push
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    - name: Verify script exists
      run: ls -la generar_noticias.py || echo "Error: Script not found in root"
    - name: Generate noticias.html
      run: |
        python generar_noticias.py || { echo "Error: Python script failed"; cat generar_noticias.py; exit 1; }
        ls -la noticias.html || echo "Error: noticias.html not generated"
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add noticias.html
        git diff --quiet && echo "No changes to commit" || (git commit -m "Actualizar noticias RSS" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
