name: Update News
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install feedparser
    - name: Generate noticias.html
      run: |
        python generar_noticias.py
        [ -f noticias.html ] && echo "File generated" || { echo "Error: noticias.html not generated"; exit 1; }
    - name: Commit and push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add noticias.html
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Actualizar noticias RSS"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
