name: Update News
on:
  workflow_dispatch:  # Habilita el botón "Run workflow"
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install feedparser
    - name: Generate noticias.html
      run: |
        python generar_noticias.py
        if [ -f noticias.html ]; then echo "File generated"; else echo "Error: noticias.html not generated"; exit 1; fi
    - name: Commit and push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add noticias.html
        git commit -m "Actualizar noticias RSS" -a || echo "No changes"
        git push
